/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fgc;

import bo.Student;
import bo.Mentor;
import dao.MentorHandler;
import dao.StudentHandler;
import java.awt.Toolkit;
import java.beans.PropertyVetoException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.HashMap;
import java.util.List;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JInternalFrame;
import javax.swing.table.DefaultTableModel;
import utils.GlobalData;
import utils.SQLUtil;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import fgc.FrmAddMentors;
import fgc.FrmUpdateMentor;

/**
 *
 * @author vande
 */
public class FrmMain extends javax.swing.JFrame {

/**
     * Creates new form FrmMain
     */
    FrmLogin frmLogin = new FrmLogin();
    FrmAddStudent frmAddStudent = new FrmAddStudent();
    FrmViewStudent frmViewStudent = new FrmViewStudent();
    FrmViewMentor frmViewMentor = new FrmViewMentor();
    FrmUpdateStudent frmUpdateStudent = new FrmUpdateStudent();
    FrmAddMentors frmAddMentors = new FrmAddMentors();
    FrmUpdateMentor frmUpdateMentor = new FrmUpdateMentor();
    
    Map<String, JInternalFrame>  forms = new HashMap<>();
    
    
    
    List<Student> students;
    
   
    
    public FrmMain() {
        initComponents();
        forms.put("frmLogin", frmLogin);
        forms.put("frmAddStudent", frmAddStudent);
        forms.put("frmUpdateStudent", frmUpdateStudent);
        forms.put("frmUpdateMentor", frmUpdateMentor);
        forms.put("frmAddMentors", frmAddMentors); 
        forms.put("frmViewStudent", frmViewStudent);
        forms.put("frmViewMentor", frmViewMentor);
       // forms.put("frmViewMentors", frmViewStudent);


        //Add add these to the JDesktopPage
        forms.values().forEach((frm)->{
            jdpMainContainer.add(frm);
        });    
    }
    private void showForm(String frmName){
        showForm(frmName,true);
    }
    private void showForm(String frmName, boolean checkLogin){
        if(checkLogin && GlobalData.mtr == null){
            showForm("frmLogin", false);
        }else{ 
             try {  
            //Do Authorization
            if(forms.get(frmName).isClosed()){
                
                try {
                    //Create new
                   forms.put(frmName, forms.get(frmName).getClass().newInstance());
                   jdpMainContainer.add(forms.get(frmName));
                } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                
            }
            forms.get(frmName).setVisible(true);
         
            forms.get(frmName).setSelected(true);
            } catch (PropertyVetoException ex) {
                java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpMainContainer = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        fileLogin = new javax.swing.JMenuItem();
        fileLogout = new javax.swing.JMenuItem();
        fileExit = new javax.swing.JMenuItem();
        menuManage = new javax.swing.JMenu();
        mngStudent = new javax.swing.JMenu();
        mngStudentAdd = new javax.swing.JMenuItem();
        mngStudentUpdate = new javax.swing.JMenuItem();
        mngMentor = new javax.swing.JMenu();
        mngMentorAdd = new javax.swing.JMenuItem();
        mngMentorUpdate = new javax.swing.JMenuItem();
        menuView = new javax.swing.JMenu();
        viewTables = new javax.swing.JMenu();
        viewStudents = new javax.swing.JMenuItem();
        viewMentors = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpMainContainer.setBackground(java.awt.Color.black);
        jdpMainContainer.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jdpMainContainer.setToolTipText("");

        javax.swing.GroupLayout jdpMainContainerLayout = new javax.swing.GroupLayout(jdpMainContainer);
        jdpMainContainer.setLayout(jdpMainContainerLayout);
        jdpMainContainerLayout.setHorizontalGroup(
            jdpMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1799, Short.MAX_VALUE)
        );
        jdpMainContainerLayout.setVerticalGroup(
            jdpMainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 917, Short.MAX_VALUE)
        );

        getContentPane().add(jdpMainContainer, java.awt.BorderLayout.CENTER);

        menuFile.setText("File");

        fileLogin.setText("Login");
        fileLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLoginActionPerformed(evt);
            }
        });
        menuFile.add(fileLogin);

        fileLogout.setText("Logout");
        fileLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileLogoutActionPerformed(evt);
            }
        });
        menuFile.add(fileLogout);

        fileExit.setText("Exit Application");
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        menuFile.add(fileExit);

        jMenuBar1.add(menuFile);

        menuManage.setText("Manage");

        mngStudent.setText("Student");

        mngStudentAdd.setText("Add");
        mngStudentAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngStudentAddActionPerformed(evt);
            }
        });
        mngStudent.add(mngStudentAdd);

        mngStudentUpdate.setText("Update");
        mngStudentUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngStudentUpdateActionPerformed(evt);
            }
        });
        mngStudent.add(mngStudentUpdate);

        menuManage.add(mngStudent);

        mngMentor.setText("Mentor");

        mngMentorAdd.setText("Add");
        mngMentorAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngMentorAddActionPerformed(evt);
            }
        });
        mngMentor.add(mngMentorAdd);

        mngMentorUpdate.setText("Update");
        mngMentorUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mngMentorUpdateActionPerformed(evt);
            }
        });
        mngMentor.add(mngMentorUpdate);

        menuManage.add(mngMentor);

        jMenuBar1.add(menuManage);

        menuView.setText("View");

        viewTables.setText("Tables");

        viewStudents.setText("Students");
        viewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentsActionPerformed(evt);
            }
        });
        viewTables.add(viewStudents);

        viewMentors.setText("Mentors");
        viewMentors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewMentorsActionPerformed(evt);
            }
        });
        viewTables.add(viewMentors);

        menuView.add(viewTables);

        jMenuBar1.add(menuView);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLogoutActionPerformed
        // TODO add your handling code here:
        GlobalData.mtr = null;
        for(Map.Entry<String, JInternalFrame> entry : forms.entrySet())
        {
            JInternalFrame value = entry.getValue();
            value.dispose();
        }
        JOptionPane.showMessageDialog(this,"LogOut Succeeded");
        
    }//GEN-LAST:event_fileLogoutActionPerformed

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    private void mngStudentAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngStudentAddActionPerformed
        showForm("frmAddStudent");
    }//GEN-LAST:event_mngStudentAddActionPerformed

    private void mngStudentUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngStudentUpdateActionPerformed
        showForm("frmUpdateStudent");
    }//GEN-LAST:event_mngStudentUpdateActionPerformed

    private void mngMentorAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngMentorAddActionPerformed
        showForm("frmAddMentors");
    }//GEN-LAST:event_mngMentorAddActionPerformed

    private void mngMentorUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mngMentorUpdateActionPerformed
        // TODO add your handling code here:
        showForm("frmUpdateMentor");
    }//GEN-LAST:event_mngMentorUpdateActionPerformed

    private void fileLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileLoginActionPerformed
        showForm("frmLogin", false);
    }//GEN-LAST:event_fileLoginActionPerformed
        
    private void viewMentorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewMentorsActionPerformed
        // TODO add your handling code here:
        showForm("frmViewMentor");

    }//GEN-LAST:event_viewMentorsActionPerformed

    private void viewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentsActionPerformed
        // TODO add your handling code here:
        showForm("frmViewStudent");

       
    }//GEN-LAST:event_viewStudentsActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               FrmMain frmMain = new FrmMain();
               frmMain.setSize(Toolkit.getDefaultToolkit().getScreenSize());
               frmMain.setVisible(true);
              
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileLogin;
    private javax.swing.JMenuItem fileLogout;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpMainContainer;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenu menuManage;
    private javax.swing.JMenu menuView;
    private javax.swing.JMenu mngMentor;
    private javax.swing.JMenuItem mngMentorAdd;
    private javax.swing.JMenuItem mngMentorUpdate;
    private javax.swing.JMenu mngStudent;
    private javax.swing.JMenuItem mngStudentAdd;
    private javax.swing.JMenuItem mngStudentUpdate;
    private javax.swing.JMenuItem viewMentors;
    private javax.swing.JMenuItem viewStudents;
    private javax.swing.JMenu viewTables;
    // End of variables declaration//GEN-END:variables
}
